### PR TITLE
Update config.toml

### PR DESCRIPTION
**Pull request by kostis-christodoulou**
fixed some misplaced quotes in line 146. Should work now

### CODE REVIEW

**Comment by charlotte-soverall** [comment]
Thanks Kostis! It works now. I just have 2 mroe problems that I can't seem to solve:
1. I my brexit blog is not knitting. This happend with my aboutme blog so I removed library(knit) and then it worked but it is still not working for my brexit blog
2. I cannot see the images added in any of my codes. Is this because my code uses eg knitr::include_graphics(here::here("images", "yield_curve_parable.jpg"), error = FALSE) and so r gets confused? I have tried to add images by using image: ! but this doesn't work either. 
Please help. Thanks Kostis ! 
Screenshot 2020-10-18 at 12 51 39
Screenshot 2020-10-18 at 12 51 58

**Comment by kostis-christodoulou** [comment]
1. wht do you mean it does not knit? What error are you getting?
2.
[image: image.png]

**Comment by charlotte-soverall** [comment]
1. Brexit is only rmd file and won't knit into a html file 
Screenshot 2020-10-19 at 14 25 39
Screenshot 2020-10-19 at 14 26 05

**Comment by charlotte-soverall** [comment]
2. In my code, I have  ```{r yield_curve_challenge, echo=FALSE, out.width="100%"}
knitr::include_graphics(here::here("images", "yield_curve_challenge.png"), error = FALSE)
``` Whenever I have this code, it does not appear on my website.

![Screenshot 2020-10-19 at 14 30 21](https://user-images.githubusercontent.com/71756720/96457485-bed35200-1217-11eb-9fbc-76613ef84982.png)
![Screenshot 2020-10-19 at 14 31 00](https://user-images.githubusercontent.com/71756720/96457492-c09d1580-1217-11eb-9a03-7b90c544f9af.png)

**Comment by charlotte-soverall** [comment]
2. In my code, when I have ```{r yield_curve_challenge, echo=FALSE, out.width="100%"}
knitr::include_graphics(here::here("images", "yield_curve_challenge.png"), error = FALSE)
It does not show on my website 

Screenshot 2020-10-19 at 14 30 21
Screenshot 2020-10-19 at 14 31 00

**Comment by kostis-christodoulou** [comment]
1. you have to run blogdown::serve_site() so that any Rmds that you
changed can be rendered
2. files are refeencend under "static". For my website, I add them all in
folder "static/img" and I call them like this

[image: image.png]

**Pull request merged**
