### PR TITLE
Update config.toml

### PR DESCRIPTION
**Pull request by kostis-christodoulou**
changed the base url... it needs https

can you please  merge changes and tells me if it works?

### CODE REVIEW

**Comment by charlotte-soverall** [comment]
Thanks Kostis! I tried and it still isn't working.

**Comment by kostis-christodoulou** [comment]
can you please send me a pic of your netlify.com control panel? Something
like this....

[image: image.png]

**Comment by charlotte-soverall** [comment]
Screenshot 2020-10-15 at 16 09 12
Screenshot 2020-10-15 at 16 09 20
Screenshot 2020-10-15 at 16 09 52
Screenshot 2020-10-15 at 16 10 03

**Comment by kostis-christodoulou** [comment]
ok, the issue is that it is manual deployment and it doesnt pick up the
changes reflected on your github.

click on deploy settings, make it deploy from git, and choose
https://github.com/charlotte-soverall/my_website

let me know how you get on and if you want to do a quick zoom... you are
almost there... 99.999% :-)

**Comment by charlotte-soverall** [comment]
It works! Thank you you so much!!

**Comment by kostis-christodoulou** [comment]
I did tell you that you were almost there :-)

o glad it works.

Just remember if you add things/make changes you need to
1. render the page using blogdown::serve_site() and
2. push everything to github by add/commit/pull/push

and netlify will immediately build the new site with all changes, etc.

Do let me know if you get stuck again... and are we having the call tomorow
morning???

**Comment by charlotte-soverall** [comment]
Yes please. I am struggling with making changes/ adding information to the website. Thanks

**Comment by kostis-christodoulou** [comment]
Ok, no problem!!

**Comment by charlotte-soverall** [comment]
Hi Kostis, I am having some trouble with my website. I have made a few changes, it has been working since you helped me on Friday and I've been adding new content, but for some reason it stoped deploying tonight. Please help!

Screenshot 2020-10-15 at 11 36 25
Screenshot 2020-10-17 at 23 39 03
Screenshot 2020-10-17 at 23 39 06
Screenshot 2020-10-17 at 23 39 08

**Comment by charlotte-soverall** [comment]
Hi Kostis, I am having some trouble with my website. I has been working since you helped me on Friday, and I have been adding new content, but it stoped deploying tonght. I don't understand the error code. Please help!
Screenshot 2020-10-17 at 23 39 03
Screenshot 2020-10-17 at 23 39 06
Screenshot 2020-10-17 at 23 39 08

**Pull request merged**
